### PR TITLE
Fix timeout handling

### PR DESCRIPTION
**Pull request by chewrocca**
Fix timeout handling in FetchMirrorLags and FetchUnavailableMirrors functions.

This PR updates the FetchMirrorLags and FetchUnavailableMirrors methods to properly handle timeout and network-related errors without panicking.
Previously, the code assumed all errors were *artifactory.APIError and performed an unsafe type assertion, which caused a panic if a different error type (e.g., *url.Error) occurred — such as when a timeout was reached.

This was discovered while scraping /metrics via Prometheus and using a reverse proxy. When Artifactory took too long to respond, the exporter panicked due to improper error handling.

```bash
panic: interface conversion: error is *url.Error, not *artifactory.APIError
time=2025-04-01T18:36:43.579Z level=ERROR msg="There was an error making API call" endpoint=https://artifactory.example.com/artifactory/api/federation/status/mirrorsLag err="Get \"https://artifactory.example.com/artifactory/api/federation/status/mirrorsLag\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

goroutine 103997 [running]:
github.com/peimanja/artifactory_exporter/artifactory.(*Client).FetchMirrorLags(0xc00025c1b0)
	/go/artifactory_exporter/artifactory/federation.go:38 +0x33a
github.com/peimanja/artifactory_exporter/collector.(*Exporter).exportFederationMirrorLags(0xc000235ab0, 0x94f1c1?)
	/go/artifactory_exporter/collector/federation.go:11 +0x38
github.com/peimanja/artifactory_exporter/collector.(*Exporter).scrape(0xc000235ab0, 0xc0002e87e0?)
	/go/artifactory_exporter/collector/collector.go:188 +0x2c5
github.com/peimanja/artifactory_exporter/collector.(*Exporter).Collect(0xc000235ab0, 0xc000151f60?)
	/go/artifactory_exporter/collector/collector.go:132 +0x75
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/registry.go:446 +0x102
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 103993
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/registry.go:538 +0xb4b

time=2025-04-01T18:37:01.039Z level=INFO msg="Starting artifactory_exporter" version="(version=v1.15.1, branch=refs/tags/v1.15.1, revision=8fb37cdb73624c7d40f2d980cc2d9603cb1a5948)"
time=2025-04-01T18:37:01.039Z level=INFO msg="Build context" context="(go=go1.21.13, user=github-actions, date=2025-02-27T17:08:02Z)"
time=2025-04-01T18:37:01.039Z level=INFO msg="Listening on address" address=:9531
```

Reproduced using `artifactory_exporter v1.15.1` with `Prometheus v2.53.1` and Artifactory behind a proxy with long response times.

### CODE REVIEW

File: artifactory/federation.go [hunk 1]
```diff
@@ -33,17 +33,24 @@ type MirrorLags struct {
 func (c *Client) FetchMirrorLags() (MirrorLags, error) {
 	var mirrorLags MirrorLags
 	c.logger.Debug("Fetching mirror lags")
+
 	resp, err := c.FetchHTTP(federationMirrorsLagEndpoint)
 	if err != nil {
-		if err.(*APIError).status == 404 {
```
Comment (KacperPerschke) [inline artifactory/federation.go:38]: Replacing the construction from line 38 with construction in line 41 pleases me very much. Full support from me!

File: artifactory/federation.go [hunk 2]
```diff
@@ -53,34 +60,31 @@ func (c *Client) FetchMirrorLags() (MirrorLags, error) {
...
-	NodeId             string
-}
-
 // FetchUnavailableMirrors makes the API call to federation/status/unavailableMirrors endpoint and returns []UnavailableMirror
 func (c *Client) FetchUnavailableMirrors() (UnavailableMirrors, error) {
 	var unavailableMirrors UnavailableMirrors
 	c.logger.Debug("Fetching unavailable mirrors")
-	resp, err := c.FetchHTTP(federationUnavailableMirrorsEndpoint)
+
+	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second) // Set a timeout duration
```
Comment (KacperPerschke) [inline artifactory/federation.go:68]: Canonical use of ctx to impose a constraint on execution time. Bravo!

**Review by KacperPerschke — COMMENTED** [review]
I have not analysed whether types `UnavailableMirror` and `UnavailableMirrors` can be removed.

I like the nature of the change and the solutions used in it very much.

**Comment by KacperPerschke** [comment]
1. It needs rebase to commit ee6ca016bdc620d61f6436599bfa9c03a66b3dac
2. I did pull it and tried to `go build` and got errors, which implies the need for a little deeper analysis. 

`go build` errors:
```
# github.com/peimanja/artifactory_exporter/artifactory
artifactory/federation.go:40:15: undefined: url
artifactory/federation.go:41:6: undefined: errors
artifactory/federation.go:43:13: undefined: errors
artifactory/federation.go:64:45: undefined: UnavailableMirrors
artifactory/federation.go:65:25: undefined: UnavailableMirrors
artifactory/federation.go:68:17: undefined: context
artifactory/federation.go:68:61: undefined: time
artifactory/federation.go:71:17: c.FetchHTTPWithContext undefined (type *Client has no field or method FetchHTTPWithContext)
artifactory/federation.go:74:15: undefined: url
artifactory/federation.go:75:6: undefined: errors
artifactory/federation.go:75:6: too many errors
```

Rather, it looks quite simple to solve. Sorry, but I do not have the time to sit down to this at the moment.

@chewrocca could you, please, rebase to master?

File: artifactory/federation.go [hunk 3]
```diff
@@ -53,34 +78,31 @@ func (c *Client) FetchMirrorLags() (MirrorLags, error) {
...
+	defer cancel()
+
+	resp, err := c.FetchHTTPWithContext(ctx, federationUnavailableMirrorsEndpoint) // Assume FetchHTTPWithContext handles context
```
Comment (KacperPerschke) [inline artifactory/federation.go:89]: @chewrocca, if you have provided `FetchHTTPWithContext` please consider removing comment in this line.

**Review by KacperPerschke — APPROVED** [review]
Commit `3a74e7a` compiles with go1.23.5 brilliantly.

I can learn from @chewrocca to create clear code that is in line with the ideology behind the go language team. I wish this project more collaborators like him.

A minor comment regarding the comment is for consideration by the author of the PR or the owner of the repository.

**Review by peimanja — APPROVED** [review]
LGTM
